### ISSUE TITLE
Missing download/contact capture page for free data sets

### ISSUE THREAD

**Issue by celrae** [energy7/datastore#3]
The free product data download is missing a form: the "agree to terms and give us your contact info" contact form isn't among our pages. I had always glossed this, since it's the same as the premium contact form, except that the contact info is optional (current store has this as required) -- and, it now occurrs to me, the data terms of use are displayed. 
https://projects.propublica.org/data-store/sets/health-hepc-prescribers-1

Right now, looks like the "download" link doesn't go anywhere, so not sure if you haven't made the contact form yet, or if it's missing from our plan.

**Comment by energy7** [comment]
@celrae It's missing, I thought you wanted to remove that step. It's no problem to make another page and form.
