### ISSUE TITLE
Missing download option: off-site free product that isn't on GitHub

### ISSUE THREAD

**Issue by celrae** [energy7/datastore#4]
Not all of the "link" downloads take you to GitHub -- some take you to other websites. (e.g., Nursing Home Compare on this page): https://projects.propublica.org/data-store/

The icon for the off-site download is a GitHub image; what happens if it's not on our site and isn't a GitHub page?

**Comment by energy7** [comment]
@celrae That's an "exit to app" icon from Material Icons, not the Github logo https://design.google.com/icons/#ic_exit_to_app — we can use another one if it's not clear

**Comment by celrae** [comment]
Oops! I think I was looking at an old mock, not the live site. 😳
