### ISSUE TITLE
Free download where premium product exists

### ISSUE THREAD

**Issue by celrae** [energy7/datastore#9]
Currently, we have a prominent upsell flag at the top of these pages. 
https://projects.propublica.org/data-store/sets/health-mcd12-2

I like the premium boxes at the bottom, but can we add a visual indicator at the top or something? Maybe out of scope, but would like to do that if possible. With longer text, I realized how far below the fold those promos are. I think they'll get lost.

**Comment by energy7** [comment]
@celrae It's no problem to add a simple anchor link, you could add some smooth scrolling behavior to it too.
